### ISSUE TITLE
doc and doc_items should be optional dependency

### ISSUE THREAD

**Issue by bell07** [dacmot/sfcraftguide#1]
Not all users like the reveal mechanism or use doc and doc_items mods.
Both mods should be optional. If not present, the "reveal.lua" is not loaded and all recipes are always visible.

By the way, why sfinv is optional? Is there a way to use sfcraftguide without sfinv?

If sfinv is optional: Since sfinv is in MTG, it is possible the sfinv is loaded but disabled. Please do the next check:

`if minetest.global_exists("sfinv") and sfinv.enabled then`

**Comment by dacmot** [comment]
I agree doc and doc_items should be optional. I was thinking of making an independent reveal mechanism, but that would be a lot more work. Just making reveal optional is a simpler task to start.

I tried to organize the code so it could be used with any inventory system. It's still coupled with sfinv, but I think it could "work" without it.

Re-opened because lazerbeak's PR doesn't make doc and doc_items optional. It just fixes the sfinv dependency.

**Comment by dacmot** [comment]
Closed by 3df7b1eb7474fd2b209f025e18656f907b1b94cb
